services:
  gaz_con:
    image: ubuntu-desktop-ros:humble-gazebo-fortress
    ipc: host
    cpus: 14      
    environment:
      - DISPLAY=172.23.128.1:1
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.X11-unix/X0
    network_mode: host
    volumes:
      - ./SimulationFiles:/home/Catcher
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      # - /dev/ttyUSB0:/dev/ttyUSB0
    tty: true

volumes:
  SimulationFiles: