services:
  gaz_con:
    image: dockerros
    ipc: host
    cpus: 14      
    environment:
      - DISPLAY=:0
      - XAUTHORITY=/tmp/.X11-unix/X0
    network_mode: host
    volumes:
      - ./SimulationFiles:/home/Catcher
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      # - /dev/ttyUSB0:/dev/ttyUSB0
    tty: true

volumes:
  SimulationFiles: